In [10]:
import os
import requests
from getpass import getpass
import pandas as pd

SERVER_URL = "https://kf.kobotoolbox.org"
API_TOKEN = (os.getenv("KOBO_API_TOKEN") or getpass("Paste Kobo API token: ")).strip()

headers = {
    "Authorization": f"Token {API_TOKEN}",
    "Accept": "application/json",
}

# 1. Fetch the LIST of all assets instead of a specific UID
list_url = f"{SERVER_URL}/api/v2/assets/"
r = requests.get(list_url, headers=headers)
r.raise_for_status()
assets = r.json().get('results', [])

# 2. Find "GDSC_Authoring" in that list
target_asset = None
for asset in assets:
    if asset['name'].lower() == "gdsc_authoring":
        target_asset = asset
        print(f"Success! Found '{asset['name']}' with UID: {asset['uid']}")
        break

if target_asset:
    # 3. Get the data for this specific form
    data_url = target_asset.get("data")
    data_response = requests.get(data_url, headers=headers)
    data_response.raise_for_status()
    
    # 4. Convert to DataFrame
    df = pd.DataFrame(data_response.json()['results'])
    print(f"Total submissions retrieved: {len(df)}")
    display(df.head())
else:
    print("Could not find a form named 'GDSC_Authoring'. Check your spelling!")

Success! Found 'GDSC_Authoring' with UID: aYLDWSQyouaQbnWX8mcrfz
Total submissions retrieved: 2

,_id,formhub/uuid,title,creator_group,url,doi,publisher_group,rights,license_type,restrictions,...,_uuid,meta/rootUuid,_attachments,_status,_geolocation,_submission_time,_tags,_notes,_validation_status,_submitted_by
0,734907300,83360d9512d848169dbf928fea0909b1,2019 Florida Census Tracts,"[{'creator_group/creator_name': 'LSHTM', 'crea...",https://services.arcgis.com/jIL9msH9OI208GCb/a...,https://doi.org/10.17604/p318-6n41,[{'publisher_group/publisher_name': 'Universit...,Public Domain,Public Domain,"You are free to copy, distribute, transmit and...",...,00e36f49-f9ee-4896-b28d-02dd6d2823dc,uuid:00e36f49-f9ee-4896-b28d-02dd6d2823dc,[],submitted_via_web,"[None, None]",2026-04-24T17:06:38,[],[],{},davidamadi
1,736133650,83360d9512d848169dbf928fea0909b1,Magu District DEM (SRTM),"[{'creator_group/creator_name': 'David Amadi',...",https://lpdaac.usgs.gov/products/srtmgl1v003/,10.1515/sjpain-2022-0013,[{'publisher_group/publisher_name': 'NASA EOSD...,CC0 1.0 Universal,Public Domain,This data is available on request,...,43087d70-60cb-457b-b3d8-51d5ee95a846,uuid:43087d70-60cb-457b-b3d8-51d5ee95a846,[],submitted_via_web,"[None, None]",2026-04-26T17:58:17,[],[],{},davidamadi

In [12]:
# 1. Get the data URL from the asset details
data_url = asset.get("data")

# 2. Fetch the actual submissions
data_response = requests.get(data_url, headers=headers)

# 3. Now convert to DataFrame
import pandas as pd
df = pd.DataFrame(data_response.json()['results'])

# Show results
print(f"Total submissions: {len(df)}")
df.head()

Total submissions: 2

,_id,formhub/uuid,title,creator_group,url,doi,publisher_group,rights,license_type,restrictions,...,_uuid,meta/rootUuid,_attachments,_status,_geolocation,_submission_time,_tags,_notes,_validation_status,_submitted_by
0,734907300,83360d9512d848169dbf928fea0909b1,2019 Florida Census Tracts,"[{'creator_group/creator_name': 'LSHTM', 'crea...",https://services.arcgis.com/jIL9msH9OI208GCb/a...,https://doi.org/10.17604/p318-6n41,[{'publisher_group/publisher_name': 'Universit...,Public Domain,Public Domain,"You are free to copy, distribute, transmit and...",...,00e36f49-f9ee-4896-b28d-02dd6d2823dc,uuid:00e36f49-f9ee-4896-b28d-02dd6d2823dc,[],submitted_via_web,"[None, None]",2026-04-24T17:06:38,[],[],{},davidamadi
1,736133650,83360d9512d848169dbf928fea0909b1,Magu District DEM (SRTM),"[{'creator_group/creator_name': 'David Amadi',...",https://lpdaac.usgs.gov/products/srtmgl1v003/,10.1515/sjpain-2022-0013,[{'publisher_group/publisher_name': 'NASA EOSD...,CC0 1.0 Universal,Public Domain,This data is available on request,...,43087d70-60cb-457b-b3d8-51d5ee95a846,uuid:43087d70-60cb-457b-b3d8-51d5ee95a846,[],submitted_via_web,"[None, None]",2026-04-26T17:58:17,[],[],{},davidamadi